///////////////////////////////////////////////////////////
//  Finish.cs
//  Implementation of the Class Finish
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2018 9:03:17 AM
//  Original author: paulus_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// A class that contains the Finishes
/// </summary>
public class Finish : Option {


	public const string GLOSS = "Gloss";
	public const string MATTE = "Matte";
    //Keeps track of which item is selected so we can recalculate

	public Finish(){
        items = new List<string>();
        items.Add(GLOSS);
        items.Add(MATTE);
	}

}//end Finish