///////////////////////////////////////////////////////////
//  Quantites.cs
//  Implementation of the Class Quantites
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2018 9:03:19 AM
//  Original author: paulus_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This will be a class to control the quantities allowed
/// </summary>
public class Quantites : Option
{
	private int Maximum = 100;
	private int Minimum = 1;

	public Quantites(){
        items = new List<string>();
        for (int i = Minimum; i <= Maximum; i++)
        {
            items.Add(i.ToString());
        }
	}

}//end Quantites