///////////////////////////////////////////////////////////
//  Sizes.cs
//  Implementation of the Class Sizes
//  Generated by Enterprise Architect
//  Created on:      12-Feb-2018 9:03:21 AM
//  Original author: paulus_d
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This will contain the sizes for prints
/// </summary>
public class Sizes : Option
{

	public const string SMALL =  "4 x 6";
	public const string MEDIUM = "5 x 7";
	public const string LARGE = "8 x 10";

	public Sizes(){
        items = new List<string>();
        items.Add(SMALL);
        items.Add(MEDIUM);
        items.Add(LARGE);
	}

}//end Sizes